sudo: required
services:
  - docker

before_install:
  - docker build -t grdavor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true grdavor/react-test npm test

after_success:
  - docker build -t grdavor/multi-client ./client
  - docker build -t grdavor/multi-nginx ./nginx
  - docker build -t grdavor/multi-server ./server
  - docker build -t grdavor/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push grdavor/multi-client
  - docker push grdavor/multi-nginx
  - docker push grdavor/multi-server
  - docker push grdavor/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-164433614065
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
